gns3_server: "10.35.5.72"
gns3_port: "80"

project_name: "NX-OS_mgmt_network"

nodes:
  - appliance_name: "Ethernet switch"
    os: "none"
    instances:
      - x: 0
        y: 0
  - appliance_name: "Cisco CSR1000v 17.03"
    os: "csr1kv"
    instances:
      - x: 0
        y: -170
        ip: "192.168.1.13 255.255.255.0"
        gw: "192.168.1.1"
  - appliance_name: "Cisco NX-OSv 9000 7.0.3"
    os: "nxos"
    instances:
      - x: -200
        y: 0
        ip: "192.168.1.11/24"
        gw: "192.168.1.1"
      - x: 200
        y: 0
        ip: "192.168.1.12/24"
        gw: "192.168.1.1"

links:
  -
    - name: "Switch1"
      interface: 1
    - name: "CiscoNX-OSv90007.0.3-1"
      interface: 0
  -
    - name: "Switch1"
      interface: 2
    - name: "CiscoNX-OSv90007.0.3-2"
      interface: 0
  -
    - name: "Switch1"
      interface: 3
    - name: "CiscoCSR1000v17.03-1"
      interface: 0